export const GET_LABELS_FILTERS = 'GET_LABELS_FILTERS';
export const GET_EMAILS = 'GET_EMAILS';
export const DELETE_FILTER = 'DELETE_FILTER';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const ADD_FILTER_CONDITION = 'ADD_FILTER_CONDITION';
export const REMOVE_FILTER_CONDITION = 'REMOVE_FILTER_CONDITION';
export const RESET_FILTER = 'RESET_FILTER';
export const CREATE_FILTER = 'CREATE_FILTER';





