// User
export const GET_LABELS_FILTERS = 'GET_LABELS_FILTERS';
export const GET_EMAILS = 'GET_EMAILS';
export const SET_LOGIN = 'SET_LOGIN';
export const RESET_STATE = 'RESET_STATE';

// Filters
export const TOGGLE_FILTER_MODAL = 'TOGGLE_FILTER_MODAL';
export const ADD_FILTER_CONDITION = 'ADD_FILTER_CONDITION';
export const REMOVE_FILTER_CONDITION = 'REMOVE_FILTER_CONDITION';
export const RESET_FILTER = 'RESET_FILTER';
export const CREATE_FILTER = 'CREATE_FILTER';
export const POPULATE_FILTER = 'POPULATE_FILTER';
export const UPDATE_STATUS = 'UPDATE_STATUS';







